version: "3" # Versión del formato de docker-compose que estamos usando

services: # Definición de los servicios que se van a ejecutar
 webapp:
  container_name: contenedor_app # Nombre del contenedor para este servicio
  restart: always
  build: . # Construir la imagen del Dockerfile en el directorio actual

  ports:
   - "5000:3000" # Mapear el puerto 5000 del host al puerto 3000 del contenedor

  links:
   - database

  volumes:
  - .:/usr/src/app # Montar el directorio actual en /usr/src/app dentro del contenedor
  
 database:
  container_name: contenedor_db # Nombre del contenedor para este servicio
  image: mongo # Usar la imagen oficial de MongoDB
  ports:
   - "27019:27017" # Mapear el puerto 27019 del host al puerto 27017 del contenedor